-- Add rich sample articles to showcase the blog design
-- Run this after 002_seed.sql

-- Clear existing sample posts (keep the one from seed)
DELETE FROM posts WHERE id > 1;

-- Add 8 engaging articles across different categories
INSERT INTO posts (slug, title, excerpt, content, cover_image, category_id, author_id, estimated_read_minutes, published_at)
VALUES

-- Faith Article 1
('when-prayer-feels-like-silence',
'When Prayer Feels Like Silence: Finding God in the Waiting',
'Ever felt like your prayers are hitting the ceiling? Here's what I learned when God seemed quietest — and how the silence taught me more than the answers ever could.',
CONCAT(
  '<p class="scripture"><strong>Truth nugget:</strong> "Be still, and know that I am God." — Psalm 46:10</p>',
  '<p>I used to think unanswered prayers meant God wasn't listening. Turns out, sometimes the answer is: "Wait. Watch. Learn what I'm doing in the silence."</p>',
  '<h2>The Uncomfortable Gift of Waiting</h2>',
  '<p>Three months. That's how long I prayed for a breakthrough that never came—at least not in the way I expected. My journal entries from that season read like a spiritual wrestling match. "God, are You even there?"</p>',
  '<p>But here's what the waiting taught me: God's silence isn't absence. It's often His loudest teaching tool.</p>',
  '<h2>What I Discovered in the Quiet</h2>',
  '<p class="pull-quote">Sometimes God's greatest gifts come wrapped in the paper of patience.</p>',
  '<p>During those months, I learned to distinguish between what I wanted and what I actually needed. The breakthrough I was begging for? Looking back, I wasn't ready for it. God was building character I'd need later.</p>',
  '<h2>Practical Ways to Navigate Silent Seasons</h2>',
  '<ul>',
  '<li><strong>Keep showing up:</strong> Even when you don't feel like it, maintain your prayer rhythm. Consistency matters more than emotion.</li>',
  '<li><strong>Journal the journey:</strong> Write down your questions, doubts, and tiny moments of hope. You'll see God's hand clearer in retrospect.</li>',
  '<li><strong>Remember past faithfulness:</strong> Look back at times God came through. He hasn't changed.</li>',
  '<li><strong>Stay in community:</strong> Don't isolate. Let others pray when your words run dry.</li>',
  '</ul>',
  '<h2>The Breakthrough You Can't See Yet</h2>',
  '<p>Here's what I wish someone told me: The breakthrough is happening even when you can't see it. God is rearranging things behind the scenes, preparing you and the answer simultaneously.</p>',
  '<p>That job you're praying for? God might be preparing you for something better. That relationship you're asking about? He might be healing wounds first. That ministry dream? He's building the foundation you'll stand on.</p>',
  '<blockquote>"Faith isn't believing God can. It's trusting He will — in His perfect timing, not ours."</blockquote>',
  '<h2>Your Turn</h2>',
  '<p>If you're in a season of waiting right now, I see you. It's hard. It's lonely sometimes. But you're not forgotten. Keep praying, even when it feels like talking to the ceiling.</p>',
  '<p>And maybe — just maybe — that silence is God saying: "Trust Me enough to wait for something better than what you're asking for."</p>',
  '<p><em>What's your experience with silent seasons? Drop a comment below or reach out — let's encourage each other.</em></p>'
),
'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='faith' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
7,
DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- Growth Article 1
('the-art-of-becoming',
'The Art of Becoming: Why Growth Feels Uncomfortable',
'Growth isn't always glamorous. Sometimes it's messy, painful, and makes you want to quit. But here's why the discomfort is actually your friend.',
CONCAT(
  '<p>Let's be honest: nobody posts their "becoming" season on Instagram. We show the butterfly, not the cocoon. The harvest, not the planting. The breakthrough, not the breakdown that came before it.</p>',
  '<p>But what if the messy middle is actually where the magic happens?</p>',
  '<h2>The Myth of Comfortable Growth</h2>',
  '<p>I used to believe that spiritual growth should feel peaceful. Like one day I'd wake up more patient, more loving, more everything good — all without the struggle.</p>',
  '<p>Reality check: Growth rarely feels peaceful while it's happening.</p>',
  '<p class="pull-quote">You can't become who you're meant to be without outgrowing who you've been.</p>',
  '<h2>Signs You're Actually Growing (Even When It Doesn't Feel Like It)</h2>',
  '<ul>',
  '<li><strong>You're uncomfortable:</strong> If everything feels too easy, you might be coasting, not growing.</li>',
  '<li><strong>Old patterns don't fit anymore:</strong> That thing you used to do? It doesn't satisfy like it used to.</li>',
  '<li><strong>Your prayers are changing:</strong> You're asking for character, not just comfort.</li>',
  '<li><strong>People notice:</strong> Even when you don't see it, others do. Listen to them.</li>',
  '<li><strong>You're asking better questions:</strong> Instead of "Why me?" you're asking "What's this teaching me?"</li>',
  '</ul>',
  '<h2>The Comparison Trap</h2>',
  '<p>Social media will make you think everyone's growing faster, healing quicker, glowing brighter. Unfollow that lie.</p>',
  '<p>Your journey is yours. Her timeline isn't your measuring stick. His breakthrough doesn't diminish your process.</p>',
  '<blockquote>"Comparison is the thief of joy — and the enemy of genuine growth."</blockquote>',
  '<h2>Practical Growth Habits That Actually Work</h2>',
  '<p><strong>1. Morning Margins:</strong> Before you check your phone, check in with God. Even 10 minutes changes everything.</p>',
  '<p><strong>2. The Mirror Test:</strong> Ask yourself weekly: "Am I becoming who I want to be? What needs to change?"</p>',
  '<p><strong>3. Accountability Circle:</strong> Find 2-3 people who'll tell you truth, not just what you want to hear.</p>',
  '<p><strong>4. Embrace the Stretch:</strong> Do one thing each week that makes you slightly uncomfortable.</p>',
  '<h2>When Growth Stalls</h2>',
  '<p>Sometimes you'll feel stuck. Like you're pedaling hard but going nowhere. Those seasons? They're not setbacks. They're setup for the next level.</p>',
  '<p>Keep going. Keep showing up. Keep choosing growth even when it's hard.</p>',
  '<p>Because one day, you'll look back and barely recognize the person you used to be — and you'll thank God for the uncomfortable journey that got you there.</p>'
),
'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='growth' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
6,
DATE_SUB(NOW(), INTERVAL 5 DAY)),

-- Womanhood Article 1
('embracing-strength-and-softness',
'Embracing Strength and Softness: The Both/And of Womanhood',
'You don't have to choose between being strong and being soft. What if you could be both — fiercely tender, gently bold?',
CONCAT(
  '<p>For years, I thought I had to pick a side. Be the "strong woman" — independent, capable, never needing help. Or be the "soft woman" — gentle, nurturing, always accommodating.</p>',
  '<p>Plot twist: I can be both. And so can you.</p>',
  '<h2>The Lie We've Been Sold</h2>',
  '<p>Society loves to put women in boxes. You're either the career woman or the homemaker. The fierce one or the gentle one. The leader or the supporter.</p>',
  '<p>But look at the women in Scripture: Deborah led armies and judged Israel. Esther displayed both courage and strategic wisdom. The Proverbs 31 woman was a businesswoman, wife, mother, and community servant — all at once.</p>',
  '<p class="pull-quote">Your softness is not weakness. Your strength is not coldness. Both are reflections of God's image in you.</p>',
  '<h2>What True Strength Looks Like</h2>',
  '<p>Real strength isn't refusing to cry. It's allowing yourself to feel deeply and still choosing hope.</p>',
  '<p>Real strength isn't doing everything alone. It's knowing when to ask for help and having the courage to receive it.</p>',
  '<p>Real strength isn't never showing vulnerability. It's being honest about your struggles while trusting God with the outcome.</p>',
  '<h2>The Power of Softness</h2>',
  '<p>Our world mistakes softness for weakness. But there's nothing weak about:</p>',
  '<ul>',
  '<li>Choosing kindness when you could choose bitterness</li>',
  '<li>Extending grace when judgment would be easier</li>',
  '<li>Staying tender in a world that's trying to make you hard</li>',
  '<li>Leading with love instead of fear</li>',
  '</ul>',
  '<blockquote>"She is clothed with strength and dignity, and she laughs without fear of the future." — Proverbs 31:25</blockquote>',
  '<h2>Permission to Be Complex</h2>',
  '<p>You can be:</p>',
  '<ul>',
  '<li>Ambitious AND content</li>',
  '<li>Independent AND interdependent</li>',
  '<li>Confident AND humble</li>',
  '<li>Strong-willed AND teachable</li>',
  '<li>Protective AND gentle</li>',
  '</ul>',
  '<p>You don't have to shrink parts of yourself to make others comfortable. God made you multifaceted for a reason.</p>',
  '<h2>Walking in Both/And</h2>',
  '<p>Here's what it looks like practically:</p>',
  '<p><strong>At work:</strong> Lead with confidence while staying open to feedback. Be assertive without being aggressive.</p>',
  '<p><strong>In relationships:</strong> Communicate your needs clearly while remaining empathetic to others.</p>',
  '<p><strong>In faith:</strong> Trust God's sovereignty while taking action on what He's placed in your hands.</p>',
  '<p><strong>In daily life:</strong> Be self-sufficient while building community. Handle business while nurturing relationships.</p>',
  '<h2>A Prayer for Us</h2>',
  '<p>God, help us embrace the fullness of who You made us to be. Give us wisdom to know when to be steel and when to be silk, when to stand firm and when to bend with grace. Let our strength serve others, and our softness heal wounds. Make us women who reflect Your heart — fierce in love, gentle in correction, bold in faith, tender in mercy.</p>',
  '<p>Amen.</p>'
),
'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='womanhood' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
6,
DATE_SUB(NOW(), INTERVAL 7 DAY)),

-- Family Article 1
('building-legacy-not-just-family',
'Building a Legacy, Not Just a Family',
'It's not about perfect family photos or Pinterest-worthy moments. It's about raising humans who'll change the world with love.',
CONCAT(
  '<p class="scripture"><strong>Truth nugget:</strong> "Train up a child in the way he should go; even when he is old he will not depart from it." — Proverbs 22:6</p>',
  '<p>Last week, I watched my daughter help a friend without being asked. No cameras. No audience. Just kindness in motion.</p>',
  '<p>And I thought: This. This is what legacy looks like.</p>',
  '<h2>Rethinking Family Success</h2>',
  '<p>We get so caught up in the visible markers of "good parenting" — grades, behavior, achievements, the right activities. But what if true success is measured in character, not credentials?</p>',
  '<p class="pull-quote">Legacy isn't what you leave FOR your children. It's what you leave IN them.</p>',
  '<h2>What We're Really Building</h2>',
  '<p>Every conversation at the dinner table. Every "I'm sorry" modeled. Every prayer whispered over sleeping heads. Every hard conversation about integrity when no one's watching.</p>',
  '<p>These moments? They're not interruptions to your legacy. They ARE your legacy.</p>',
  '<h2>Five Legacy Foundations</h2>',
  '<p><strong>1. Faith Over Fear</strong></p>',
  '<p>Teach them to run TO God in hard times, not FROM Him. Let them see you praying through problems, not just posting about blessings.</p>',
  '<p><strong>2. Character Over Comfort</strong></p>',
  '<p>It's easier to give them everything they want. It's better to teach them to work for what they need and share what they have.</p>',
  '<p><strong>3. Truth Over Trend</strong></p>',
  '<p>Culture will shift. God's Word won't. Build their lives on the foundation that never cracks.</p>',
  '<p><strong>4. Service Over Status</strong></p>',
  '<p>Show them that true greatness is found in serving others. Let them see you volunteer, help neighbors, support the marginalized.</p>',
  '<p><strong>5. Love Over Legalism</strong></p>',
  '<p>Rules without relationship breed rebellion. They need to know they're loved unconditionally, even as you guide them consistently.</p>',
  '<blockquote>"The greatest legacy we can leave our children is happy memories, strong values, and a foundation of faith."</blockquote>',
  '<h2>When You Feel Like You're Failing</h2>',
  '<p>Some days, you'll lose your patience. Say the wrong thing. React instead of respond. Welcome to the club — we meet every day.</p>',
  '<p>But here's grace: Your kids don't need perfect. They need present. They need authentic. They need parents who apologize, grow, and keep trying.</p>',
  '<p>Every day is a new chance to point them to Jesus.</p>',
  '<h2>The Long Game</h2>',
  '<p>You might not see the fruit of your labor immediately. That's okay. You're planting seeds, not demanding instant harvest.</p>',
  '<p>Keep praying. Keep modeling. Keep showing up. Keep loving them through every season.</p>',
  '<p>Twenty years from now, when they're raising their own families or impacting their communities or simply being kind humans in a harsh world, you'll see it: Your legacy, living and breathing.</p>',
  '<p>And it will be worth every sacrifice, every prayer, every moment you chose them over ease.</p>',
  '<p><em>What's one legacy value you're intentionally building into your family? Share in the comments — let's encourage each other!</em></p>'
),
'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='family' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
7,
DATE_SUB(NOW(), INTERVAL 10 DAY)),

-- Faith Article 2
('everyday-worship-beyond-sunday',
'Everyday Worship: Making Monday as Sacred as Sunday',
'What if worship wasn't just a Sunday thing? What if your laundry, commute, and coffee breaks could all become acts of praise?',
CONCAT(
  '<p>I used to compartmentalize my faith: Sundays for God, Mondays through Saturdays for everything else. Then I realized — God doesn't compartmentalize. Why should I?</p>',
  '<h2>Redefining Worship</h2>',
  '<p>Worship isn't just singing songs with your eyes closed. It's any act that says: "God, You're worthy of my attention, my effort, my very life."</p>',
  '<p class="pull-quote">When your work becomes worship, Monday morning hits different.</p>',
  '<ul>',
  '<li>Washing dishes? That's worship — creating order from chaos, just like God spoke light into darkness.</li>',
  '<li>Sitting in traffic? Worship — thanking God for the car, the job, the breath in your lungs.</li>',
  '<li>Cooking dinner? Worship — nourishing the bodies God created, serving with love.</li>',
  '<li>Working your 9-to-5? Worship — using your gifts to glorify Him and serve others.</li>',
  '</ul>',
  '<h2>Making the Shift</h2>',
  '<p>Start small. This week, try:</p>',
  '<p><strong>Morning dedication:</strong> "God, this day is Yours. Use me."</p>',
  '<p><strong>Task transformation:</strong> Before mundane tasks, pray: "Let this glorify You."</p>',
  '<p><strong>Gratitude pauses:</strong> Set phone reminders to thank God throughout the day.</p>',
  '<p><strong>Evening reflection:</strong> "Where did I see You today?"</p>',
  '<blockquote>"Whether you eat or drink, or whatever you do, do all to the glory of God." — 1 Corinthians 10:31</blockquote>',
  '<p>Your whole life can become an offering. Every moment, an opportunity to say: "God, You're worthy."</p>'
),
'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='faith' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
5,
DATE_SUB(NOW(), INTERVAL 14 DAY)),

-- Growth Article 2
('healing-isnt-linear',
'Healing Isn't Linear: Embracing the Zigzag Journey',
'Two steps forward, one step back, three steps sideways — and still making progress. This is what healing actually looks like.',
CONCAT(
  '<p>If healing was a straight line, we'd all be healed by now. But healing is more like a spiral — you revisit the same issues at deeper levels, each time with more tools, more wisdom, more grace.</p>',
  '<h2>The Myth of "I'm Over It"</h2>',
  '<p>We love to declare victory: "I'm healed! I'm over it! That's in the past!" Then something triggers the old wound and we feel like failures.</p>',
  '<p>But here's truth: Having a bad day doesn't erase your progress. Feeling the pain again doesn't mean you're back at square one.</p>',
  '<p class="pull-quote">Progress isn't perfection. It's choosing healing even when it would be easier to stay broken.</p>',
  '<h2>What Real Healing Looks Like</h2>',
  '<ul>',
  '<li>You recognize triggers faster</li>',
  '<li>You respond with wisdom, not just reaction</li>',
  '<li>You give yourself grace on hard days</li>',
  '<li>You celebrate small victories</li>',
  '<li>You're honest about where you still struggle</li>',
  '</ul>',
  '<p>Healing isn't about never feeling pain. It's about pain no longer controlling you.</p>',
  '<h2>Permission to Not Be "Fixed"</h2>',
  '<p>You're not a project that needs completion. You're a person on a journey. Some wounds leave scars. Some healing takes a lifetime. That doesn't make you broken — it makes you human.</p>',
  '<p>God isn't frustrated with your process. Why should you be?</p>',
  '<blockquote>"He heals the brokenhearted and binds up their wounds." — Psalm 147:3</blockquote>',
  '<p>Keep going. Keep healing. Keep giving yourself the same compassion you'd give your best friend.</p>',
  '<p>The zigzag is part of the journey. And you're doing better than you think.</p>'
),
'https://images.unsplash.com/photo-1517677129300-07b130802f46?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='growth' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
6,
DATE_SUB(NOW(), INTERVAL 17 DAY)),

-- Womanhood Article 2
('the-comparison-game',
'Escaping the Comparison Game: Your Journey Is Enough',
'She's more successful. She's more beautiful. She has it all together. But here's the truth: Her highlight reel isn't your behind-the-scenes.',
CONCAT(
  '<p>Three years ago, I almost quit blogging because someone else's platform was growing faster. I felt invisible, inadequate, behind.</p>',
  '<p>Then God whispered: "I gave you your race. Why are you trying to run hers?"</p>',
  '<h2>The Thief Called Comparison</h2>',
  '<p>Comparison will rob you blind if you let it. It steals your joy, your confidence, your peace, and your progress.</p>',
  '<p class="pull-quote">You can admire someone's journey without abandoning your own.</p>',
  '<h2>The Social Media Trap</h2>',
  '<p>Instagram shows the victory, not the valley. The harvest, not the years of planting. The breakthrough, not the breakdowns that came before it.</p>',
  '<p>You're comparing your chapter 3 to her chapter 20. Stop it.</p>',
  '<h2>Finding Freedom</h2>',
  '<p><strong>Unfollow strategically:</strong> If it doesn't inspire you, unfollow. Protect your peace.</p>',
  '<p><strong>Celebrate others genuinely:</strong> Her success doesn't diminish yours. There's room for all of us to win.</p>',
  '<p><strong>Focus on your lane:</strong> What has God called YOU to do? Stay there.</p>',
  '<p><strong>Track your own progress:</strong> Look how far YOU've come, not how far she is ahead.</p>',
  '<blockquote>"Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else." — Galatians 6:4</blockquote>',
  '<p>Your story is uniquely yours. Live it fully, unapologetically, and comparison-free.</p>'
),
'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='womanhood' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
5,
DATE_SUB(NOW(), INTERVAL 20 DAY)),

-- Family Article 2
('imperfect-family-perfect-love',
'Imperfect Family, Perfect Love: Grace in the Chaos',
'Your family doesn't have to be perfect to be good. Sometimes messy, loud, and chaotic IS the blessing.',
CONCAT(
  '<p>Last night, dinner was burnt, homework wasn't done, and we all went to bed without resolving an argument. And you know what? We're still a good family.</p>',
  '<h2>The Perfect Family Myth</h2>',
  '<p>Social media sells perfection: matching outfits, peaceful breakfasts, kids who never fight. Real life? It's messier. And that's okay.</p>',
  '<p class="pull-quote">Perfect families don't exist. But families filled with imperfect love? Those can change the world.</p>',
  '<h2>What Actually Matters</h2>',
  '<ul>',
  '<li><strong>Showing up:</strong> Even on hard days, you keep choosing each other.</li>',
  '<li><strong>Saying sorry:</strong> Teaching kids that "I was wrong" is powerful.</li>',
  '<li><strong>Laughing together:</strong> Joy in chaos is a spiritual weapon.</li>',
  '<li><strong>Praying through problems:</strong> Letting them see faith in action.</li>',
  '</ul>',
  '<h2>Grace for the Hard Days</h2>',
  '<p>Some days you'll mess up. You'll yell when you meant to talk calmly. You'll be impatient when they need understanding.</p>',
  '<p>That's when grace shows up — for you and for them.</p>',
  '<blockquote>"Above all, love each other deeply, because love covers over a multitude of sins." — 1 Peter 4:8</blockquote>',
  '<p>Your family doesn't need perfect. They need presence, patience, and pizza nights where everyone talks about their day.</p>',
  '<p>Keep showing up. Keep loving through the mess. That's where the real memories are made.</p>'
),
'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=1200&q=80',
(SELECT id FROM categories WHERE slug='family' LIMIT 1),
(SELECT id FROM users WHERE email='ruth@ruthspeakstruth.com.ng' LIMIT 1),
5,
DATE_SUB(NOW(), INTERVAL 24 DAY));
